import type { IntegrationProviderPack } from "../provider-pack";
import { createAirtablePack } from "./airtable";
import {
  createConfluencePack,
  createJiraPack,
  createJiraServiceManagementPack,
} from "./atlassian";
import {
  createAppConfigPack,
  createAthenaPack,
  createCloudFormationPack,
  createCloudWatchPack,
  createCodePipelinePack,
  createDynamoDbPack,
  createIamPack,
  createIdentityCenterPack,
  createRdsPack,
  createS3Pack,
  createSecretsManagerPack,
  createSesPack,
  createSqsPack,
  createStsPack,
  createTextractPack,
} from "./aws";
import { createCloudflarePack } from "./cloudflare";
import {
  createAzureAdPack,
  createMicrosoftExcelPack,
  createMicrosoftPlannerPack,
  createMicrosoftTeamsPack,
  createOneDrivePack,
  createOutlookPack,
  createSharePointPack,
} from "./microsoft-graph";
import {
  createClickHousePack,
  createJupyterPack,
  createMongoDbPack,
  createMySqlPack,
  createNeo4jPack,
  createPostgreSqlPack,
  createRedisPack,
  createSftpPack,
  createSshPack,
} from "./protocol";
import {
  createArxivPack,
  createBrandfetchPack,
  createCalendlyPack,
  createDiscordPack,
  createExaPack,
  createHunterIoPack,
  createJinaPack,
  createLinkedInPack,
  createPagerDutyPack,
  createPerplexityPack,
  createSendGridPack,
  createTavilyPack,
  createTelegramPack,
  createTypeformPack,
  createWebflowPack,
  createWikipediaPack,
} from "./rest";
import {
  createAlgoliaPack,
  createAzureDevOpsPack,
  createBoxPack,
  createCalComPack,
  createClerkPack,
  createDatadogPack,
  createDocuSignPack,
  createElasticsearchPack,
  createGoogleAppSheetPack,
  createGoogleBigQueryPack,
  createGoogleMapsPack,
  createGoogleTranslatePack,
  createGoogleVaultPack,
  createOktaPack,
  createPineconePack,
  createQdrantPack,
  createRedditPack,
  createSalesforcePack,
  createShopifyPack,
  createSupabasePack,
  createTemporalPack,
  createTrelloPack,
  createTwilioVoicePack,
  createUpstashPack,
  createXPack,
  createZendeskPack,
} from "./vendor";
import { createVercelPack } from "./vercel";

/**
 * Every provider pack the package ships, in one list.
 *
 * This is the single place a new provider is registered. The registry builder
 * and the coverage gate both read it, so a pack cannot be executable without
 * being coverage-checked, or coverage-checked without being executable — the
 * two used to be separate hand-maintained lists and could drift.
 *
 * Packs gate themselves on the runtimes they need, returning no adapters when
 * a product has not configured one, so the list needs no per-entry wiring.
 */
export const BUILT_IN_PROVIDER_PACKS: readonly IntegrationProviderPack[] = [
  createAirtablePack(),
  createAlgoliaPack(),
  createAppConfigPack(),
  createArxivPack(),
  createAthenaPack(),
  createAzureAdPack(),
  createAzureDevOpsPack(),
  createBoxPack(),
  createBrandfetchPack(),
  createCalComPack(),
  createCalendlyPack(),
  createClerkPack(),
  createClickHousePack(),
  createCloudFormationPack(),
  createCloudWatchPack(),
  createCloudflarePack(),
  createCodePipelinePack(),
  createConfluencePack(),
  createDatadogPack(),
  createDiscordPack(),
  createDocuSignPack(),
  createDynamoDbPack(),
  createElasticsearchPack(),
  createExaPack(),
  createGoogleAppSheetPack(),
  createGoogleBigQueryPack(),
  createGoogleMapsPack(),
  createGoogleTranslatePack(),
  createGoogleVaultPack(),
  createHunterIoPack(),
  createIamPack(),
  createIdentityCenterPack(),
  createJinaPack(),
  createJiraPack(),
  createJiraServiceManagementPack(),
  createJupyterPack(),
  createLinkedInPack(),
  createMicrosoftExcelPack(),
  createMicrosoftPlannerPack(),
  createMicrosoftTeamsPack(),
  createMongoDbPack(),
  createMySqlPack(),
  createNeo4jPack(),
  createOktaPack(),
  createOneDrivePack(),
  createOutlookPack(),
  createPagerDutyPack(),
  createPerplexityPack(),
  createPineconePack(),
  createPostgreSqlPack(),
  createQdrantPack(),
  createRdsPack(),
  createRedditPack(),
  createRedisPack(),
  createS3Pack(),
  createSalesforcePack(),
  createSecretsManagerPack(),
  createSendGridPack(),
  createSesPack(),
  createSftpPack(),
  createSharePointPack(),
  createShopifyPack(),
  createSqsPack(),
  createSshPack(),
  createStsPack(),
  createSupabasePack(),
  createTavilyPack(),
  createTelegramPack(),
  createTemporalPack(),
  createTextractPack(),
  createTrelloPack(),
  createTwilioVoicePack(),
  createTypeformPack(),
  createUpstashPack(),
  createVercelPack(),
  createWebflowPack(),
  createWikipediaPack(),
  createXPack(),
  createZendeskPack(),
];
