import {
  createIntegrationCredentialReference,
  createIntegrationCredentialKeyring,
  decryptIntegrationApiKeyCredential,
  decryptIntegrationConnectionLinkCredential,
  decryptIntegrationCredential,
  encryptIntegrationApiKeyCredential,
  encryptIntegrationConnectionLinkCredential,
  encryptIntegrationCredential,
  EncryptedIntegrationCredentialSchema,
  IntegrationApiKeyCredentialSchema,
  IntegrationConnectionLinkCredentialSchema,
  IntegrationCredentialError,
  IntegrationCredentialReferenceSchema,
  MergeConnectionLinkCredentialSchema,
  IntegrationOAuthCredentialSchema,
  PlaidConnectionLinkCredentialSchema,
} from "./credentials";
import {
  createIntegrationConnectionLinkRuntime,
  IntegrationConnectionLinkError,
} from "./connection-link";
import {
  createIntegrationWebhookRoutes,
  createIntegrationWebhookRuntime,
  IntegrationWebhookError,
} from "./webhook";
import {
  createIntegrationApiKeyRuntime,
  createBuiltInIntegrationApiKeyRuntime,
  BUILT_IN_API_KEY_PROVIDER_CONFIGURATIONS,
  IntegrationApiKeyRuntimeError,
} from "./api-key-runtime";
import {
  createIntegrationNoAuthRuntime,
  IntegrationNoAuthRuntimeError,
} from "./no-auth-runtime";
import { createApiKeyProviderSdk, ApiKeyProviderError } from "./api-key";
import {
  createOAuth2ProviderSdk,
  createAirtableOAuth2Provider,
  createAsanaOAuth2Provider,
  createDropboxOAuth2Provider,
  createHubSpotOAuth2Provider,
  createGoogleCalendarOAuth2Provider,
  createGoogleDriveOAuth2Provider,
  createGoogleSheetsOAuth2Provider,
  createGoogleDocsOAuth2Provider,
  createGoogleSlidesOAuth2Provider,
  createGmailOAuth2Provider,
  createGoogleFormsOAuth2Provider,
  createGoogleTasksOAuth2Provider,
  createGoogleContactsOAuth2Provider,
  createGoogleMeetOAuth2Provider,
  createGoogleGroupsOAuth2Provider,
  createLinearOAuth2Provider,
  createQuickBooksOAuth2Provider,
  createSlackOAuth2Provider,
  createXeroOAuth2Provider,
  OAuth2ProviderError,
} from "./oauth2";
import {
  createUnauthenticatedProviderSdk,
  UnauthenticatedProviderError,
} from "./unauthenticated";
import {
  createSlackProviderSdk,
  createHubSpotProviderSdk,
  createGitHubProviderSdk,
  createGitLabProviderSdk,
  createCloudflareProviderSdk,
  createElevenLabsProviderSdk,
  createFirecrawlProviderSdk,
  createAirtableProviderSdk,
  createAsanaProviderSdk,
  createDropboxProviderSdk,
  createMailgunProviderSdk,
  createIntercomProviderSdk,
  createLinearProviderSdk,
  createMailchimpProviderSdk,
  createVercelProviderSdk,
  createSquareProviderSdk,
  createGoogleCalendarProviderSdk,
  createGoogleDriveProviderSdk,
  createGoogleSheetsProviderSdk,
  createGoogleDocsProviderSdk,
  createGoogleSlidesProviderSdk,
  createGmailProviderSdk,
  createGoogleFormsProviderSdk,
  createGoogleTasksProviderSdk,
  createGoogleContactsProviderSdk,
  createGoogleBooksProviderSdk,
  createYouTubeProviderSdk,
  createResendProviderSdk,
  createBrexProviderSdk,
  createQuickBooksProviderSdk,
  createXeroProviderSdk,
  createPlaidProviderSdk,
  createMergeProviderSdk,
  createGoogleMeetProviderSdk,
  createGoogleGroupsProviderSdk,
  createStripeProviderSdk,
  getSlackProviderSdkReport,
  getHubSpotProviderSdkReport,
  getGitHubProviderSdkReport,
  getGitLabProviderSdkReport,
  getCloudflareProviderSdkReport,
  getElevenLabsProviderSdkReport,
  getFirecrawlProviderSdkReport,
  getAirtableProviderSdkReport,
  getAsanaProviderSdkReport,
  getDropboxProviderSdkReport,
  getMailgunProviderSdkReport,
  getIntercomProviderSdkReport,
  getLinearProviderSdkReport,
  getMailchimpProviderSdkReport,
  getVercelProviderSdkReport,
  getSquareProviderSdkReport,
  getGoogleCalendarProviderSdkReport,
  getGoogleDriveProviderSdkReport,
  getGoogleSheetsProviderSdkReport,
  getGoogleDocsProviderSdkReport,
  getGoogleSlidesProviderSdkReport,
  getGmailProviderSdkReport,
  getGoogleFormsProviderSdkReport,
  getGoogleTasksProviderSdkReport,
  getGoogleContactsProviderSdkReport,
  getGoogleBooksProviderSdkReport,
  getYouTubeProviderSdkReport,
  getResendProviderSdkReport,
  getGoogleMeetProviderSdkReport,
  getGoogleGroupsProviderSdkReport,
  getBrexProviderSdkReport,
  getQuickBooksProviderSdkReport,
  getXeroProviderSdkReport,
  getPlaidProviderSdkReport,
  getMergeProviderSdkReport,
  createIntegrationProviderSdkRegistry,
  createBuiltInProviderSdkRegistry,
  getProviderSdkCoverageReport,
  getStripeProviderSdkReport,
  IntegrationProviderSdkError,
} from "./provider-sdk";
import { createIntegrationTypedRestProvider } from "./provider-rest";
import { createIntegrationSpecialProvider } from "./provider-special";
import {
  createInMemoryIntegrationCredentialRefreshLock,
  createInMemoryIntegrationOAuthStateStore,
  createIntegrationOAuthRuntime,
  IntegrationRuntimeError,
  PendingIntegrationOAuthAuthorizationSchema,
} from "./runtime";
import {
  composeIntegrationRoutes,
  createApiKeyRouteConnector,
  createIntegrationApiKeyRoutes,
  createIntegrationConnectionLinkRoutes,
  createIntegrationNoAuthRoutes,
  createIntegrationOAuthRoutes,
  createIntegrationProductRoutes,
  createIntegrationProviderExecutionRoutes,
  createNoAuthRouteConnector,
  createOAuthRouteConnector,
} from "./routes";

if (typeof window !== "undefined") {
  throw new Error(
    "@oppulence/integrations/server is server-only and must not run in a browser.",
  );
}

// Keep runtime imports explicit. Bun can otherwise tree-shake bare re-exports
// when this server entrypoint is bundled for publication.
export {
  createIntegrationCredentialReference,
  createIntegrationCredentialKeyring,
  decryptIntegrationApiKeyCredential,
  decryptIntegrationConnectionLinkCredential,
  decryptIntegrationCredential,
  encryptIntegrationApiKeyCredential,
  encryptIntegrationConnectionLinkCredential,
  encryptIntegrationCredential,
  EncryptedIntegrationCredentialSchema,
  IntegrationApiKeyCredentialSchema,
  IntegrationConnectionLinkCredentialSchema,
  IntegrationCredentialError,
  IntegrationCredentialReferenceSchema,
  MergeConnectionLinkCredentialSchema,
  IntegrationOAuthCredentialSchema,
  PlaidConnectionLinkCredentialSchema,
  createIntegrationConnectionLinkRuntime,
  IntegrationConnectionLinkError,
  createIntegrationWebhookRuntime,
  createIntegrationWebhookRoutes,
  IntegrationWebhookError,
  createIntegrationApiKeyRuntime,
  createBuiltInIntegrationApiKeyRuntime,
  BUILT_IN_API_KEY_PROVIDER_CONFIGURATIONS,
  IntegrationApiKeyRuntimeError,
  createIntegrationNoAuthRuntime,
  IntegrationNoAuthRuntimeError,
  createOAuth2ProviderSdk,
  createAirtableOAuth2Provider,
  createAsanaOAuth2Provider,
  createDropboxOAuth2Provider,
  createHubSpotOAuth2Provider,
  createGoogleCalendarOAuth2Provider,
  createGoogleDriveOAuth2Provider,
  createGoogleSheetsOAuth2Provider,
  createGoogleDocsOAuth2Provider,
  createGoogleSlidesOAuth2Provider,
  createGmailOAuth2Provider,
  createGoogleFormsOAuth2Provider,
  createGoogleTasksOAuth2Provider,
  createGoogleContactsOAuth2Provider,
  createGoogleMeetOAuth2Provider,
  createGoogleGroupsOAuth2Provider,
  createLinearOAuth2Provider,
  createQuickBooksOAuth2Provider,
  createSlackOAuth2Provider,
  createXeroOAuth2Provider,
  OAuth2ProviderError,
  createApiKeyProviderSdk,
  ApiKeyProviderError,
  createUnauthenticatedProviderSdk,
  UnauthenticatedProviderError,
  createStripeProviderSdk,
  createSlackProviderSdk,
  createHubSpotProviderSdk,
  createGitHubProviderSdk,
  createGitLabProviderSdk,
  createCloudflareProviderSdk,
  createElevenLabsProviderSdk,
  createFirecrawlProviderSdk,
  createAirtableProviderSdk,
  createAsanaProviderSdk,
  createDropboxProviderSdk,
  createMailgunProviderSdk,
  createIntercomProviderSdk,
  createLinearProviderSdk,
  createMailchimpProviderSdk,
  createVercelProviderSdk,
  createSquareProviderSdk,
  createGoogleCalendarProviderSdk,
  createGoogleDriveProviderSdk,
  createGoogleSheetsProviderSdk,
  createGoogleDocsProviderSdk,
  createGoogleSlidesProviderSdk,
  createGmailProviderSdk,
  createGoogleFormsProviderSdk,
  createGoogleTasksProviderSdk,
  createGoogleContactsProviderSdk,
  createGoogleBooksProviderSdk,
  createYouTubeProviderSdk,
  createResendProviderSdk,
  createBrexProviderSdk,
  createQuickBooksProviderSdk,
  createXeroProviderSdk,
  createPlaidProviderSdk,
  createMergeProviderSdk,
  createGoogleMeetProviderSdk,
  createGoogleGroupsProviderSdk,
  getStripeProviderSdkReport,
  getSlackProviderSdkReport,
  getHubSpotProviderSdkReport,
  getGitHubProviderSdkReport,
  getGitLabProviderSdkReport,
  getCloudflareProviderSdkReport,
  getElevenLabsProviderSdkReport,
  getFirecrawlProviderSdkReport,
  getAirtableProviderSdkReport,
  getAsanaProviderSdkReport,
  getDropboxProviderSdkReport,
  getMailgunProviderSdkReport,
  getIntercomProviderSdkReport,
  getLinearProviderSdkReport,
  getMailchimpProviderSdkReport,
  getVercelProviderSdkReport,
  getSquareProviderSdkReport,
  getGoogleCalendarProviderSdkReport,
  getGoogleDriveProviderSdkReport,
  getGoogleSheetsProviderSdkReport,
  getGoogleDocsProviderSdkReport,
  getGoogleSlidesProviderSdkReport,
  getGmailProviderSdkReport,
  getGoogleFormsProviderSdkReport,
  getGoogleTasksProviderSdkReport,
  getGoogleContactsProviderSdkReport,
  getGoogleBooksProviderSdkReport,
  getYouTubeProviderSdkReport,
  getResendProviderSdkReport,
  getGoogleMeetProviderSdkReport,
  getGoogleGroupsProviderSdkReport,
  getBrexProviderSdkReport,
  getQuickBooksProviderSdkReport,
  getXeroProviderSdkReport,
  getPlaidProviderSdkReport,
  getMergeProviderSdkReport,
  createIntegrationProviderSdkRegistry,
  createBuiltInProviderSdkRegistry,
  getProviderSdkCoverageReport,
  IntegrationProviderSdkError,
  createIntegrationTypedRestProvider,
  createIntegrationSpecialProvider,
  createIntegrationOAuthRuntime,
  createInMemoryIntegrationCredentialRefreshLock,
  createInMemoryIntegrationOAuthStateStore,
  IntegrationRuntimeError,
  PendingIntegrationOAuthAuthorizationSchema,
  createIntegrationOAuthRoutes,
  createIntegrationApiKeyRoutes,
  createIntegrationConnectionLinkRoutes,
  createIntegrationNoAuthRoutes,
  createIntegrationProductRoutes,
  createIntegrationProviderExecutionRoutes,
  composeIntegrationRoutes,
  createApiKeyRouteConnector,
  createNoAuthRouteConnector,
  createOAuthRouteConnector,
};
export type {
  EncryptedIntegrationCredential,
  IntegrationCredentialKeyring,
  IntegrationCredentialKeyDefinition,
  IntegrationCredentialReference,
  IntegrationCredentialVault,
  IntegrationApiKeyCredential,
  IntegrationConnectionLinkCredential,
  MergeConnectionLinkCredential,
  IntegrationOAuthCredential,
  PlaidConnectionLinkCredential,
} from "./credentials";
export type {
  CompleteConnectionLinkInput,
  CompleteConnectionLinkResult,
  ConnectionLinkTokenResult,
  CreateMergeLinkTokenInput,
  CreatePlaidLinkTokenInput,
  IntegrationConnectionLinkRuntime,
  IntegrationConnectionLinkRuntimeConfig,
  IntegrationConnectionLinkSubject,
  MergeConnectionLinkConfig,
  MergeLinkSdk,
  PlaidConnectionLinkConfig,
  PlaidLinkSdk,
} from "./connection-link";
export type {
  IntegrationWebhookConnection,
  IntegrationWebhookProvider,
  IntegrationWebhookRuntime,
  IntegrationWebhookRuntimeConfig,
  IntegrationWebhookRoutesConfig,
  IntegrationWebhookSyncRequest,
  MergeIntegrationWebhookConfig,
  PlaidIntegrationWebhookConfig,
  PlaidWebhookSdk,
  ProcessIntegrationWebhookResult,
} from "./webhook";
export type {
  ConnectIntegrationApiKeyInput,
  ConnectIntegrationApiKeyResult,
  IntegrationApiKeyAuthorizer,
  IntegrationApiKeyProviderRequest,
  IntegrationApiKeyRuntime,
  IntegrationApiKeyRuntimeConfig,
  BuiltInIntegrationApiKeyRuntimeConfig,
  IntegrationApiKeySubject,
} from "./api-key-runtime";
export type {
  ConnectIntegrationNoAuthInput,
  ConnectIntegrationNoAuthResult,
  IntegrationNoAuthAuthorizer,
  IntegrationNoAuthProviderRequest,
  IntegrationNoAuthRuntime,
  IntegrationNoAuthRuntimeConfig,
  IntegrationNoAuthSubject,
} from "./no-auth-runtime";
export type {
  ApiKeyProviderConfiguration,
  ApiKeyProviderRequest,
  ApiKeyProviderSdk,
} from "./api-key";
export type {
  OAuth2ApiRequest,
  OAuth2AuthorizationInput,
  OAuth2ProviderConfiguration,
  OAuth2ProviderSdk,
  AirtableOAuth2ProviderInput,
  AsanaOAuth2ProviderInput,
  DropboxOAuth2ProviderInput,
  HubSpotOAuth2ProviderInput,
  GoogleCalendarOAuth2ProviderInput,
  GoogleDriveOAuth2ProviderInput,
  GoogleSheetsOAuth2ProviderInput,
  GoogleDocsOAuth2ProviderInput,
  GoogleSlidesOAuth2ProviderInput,
  GmailOAuth2ProviderInput,
  GoogleFormsOAuth2ProviderInput,
  GoogleTasksOAuth2ProviderInput,
  GoogleContactsOAuth2ProviderInput,
  GoogleMeetOAuth2ProviderInput,
  GoogleGroupsOAuth2ProviderInput,
  LinearOAuth2ProviderInput,
  SlackOAuth2ProviderInput,
} from "./oauth2";
export type {
  UnauthenticatedProviderConfiguration,
  UnauthenticatedProviderRequest,
  UnauthenticatedProviderSdk,
} from "./unauthenticated";
export type {
  IntegrationProviderSdk,
  IntegrationProviderSdkRegistry,
  IntegrationProviderExecutionLane,
  BuiltInProviderSdkRegistryConfig,
  ProviderSdkInvocation,
  ProviderSdkResult,
  ProviderSdkCoverageReport,
  SlackProviderSdkConfig,
  HubSpotProviderSdkConfig,
  GitHubProviderSdkConfig,
  GitLabProviderSdkConfig,
  CloudflareProviderSdkConfig,
  ElevenLabsProviderSdkConfig,
  FirecrawlProviderSdkConfig,
  AirtableProviderSdkConfig,
  AsanaProviderSdkConfig,
  DropboxProviderSdkConfig,
  MailgunProviderSdkConfig,
  IntercomProviderSdkConfig,
  LinearProviderSdkConfig,
  MailchimpProviderSdkConfig,
  VercelProviderSdkConfig,
  SquareProviderSdkConfig,
  GoogleCalendarProviderSdkConfig,
  GoogleDriveProviderSdkConfig,
  GoogleSheetsProviderSdkConfig,
  GoogleDocsProviderSdkConfig,
  GoogleSlidesProviderSdkConfig,
  GmailProviderSdkConfig,
  GoogleFormsProviderSdkConfig,
  GoogleTasksProviderSdkConfig,
  GoogleContactsProviderSdkConfig,
  GoogleBooksProviderSdkConfig,
  YouTubeProviderSdkConfig,
  ResendProviderSdkConfig,
  GoogleMeetProviderSdkConfig,
  GoogleGroupsProviderSdkConfig,
  BrexProviderSdkConfig,
  MergeProviderSdkConfig,
  PlaidProviderSdkConfig,
  QuickBooksProviderSdkConfig,
  StripeProviderSdkConfig,
  XeroProviderSdkConfig,
} from "./provider-sdk";
export type {
  IntegrationTypedRestBody,
  IntegrationTypedRestMethod,
  IntegrationTypedRestOutputDefinition,
  IntegrationTypedRestOutputType,
  IntegrationTypedRestParameterDefinition,
  IntegrationTypedRestParameterItemSchema,
  IntegrationTypedRestParameterVisibility,
  IntegrationTypedRestProviderConfig,
  IntegrationTypedRestRetryConfig,
  IntegrationTypedRestTool,
  IntegrationTypedRestTransport,
} from "./provider-rest";
export type { IntegrationSpecialProviderConfig } from "./provider-special";
export type {
  BeginIntegrationOAuthInput,
  BeginIntegrationOAuthResult,
  CompleteIntegrationOAuthInput,
  CompleteIntegrationOAuthResult,
  IntegrationOAuthRuntime,
  IntegrationOAuthRuntimeConfig,
  IntegrationOAuthCompletionAuthorizer,
  IntegrationCredentialRefreshLock,
  IntegrationOAuthStateStore,
  IntegrationOAuthSubject,
  IntegrationProviderRequest,
  PendingIntegrationOAuthAuthorization,
} from "./runtime";
export type {
  IntegrationApiKeyRoutesConfig,
  IntegrationNoAuthRoutesConfig,
  IntegrationConnectionLinkRoutesConfig,
  IntegrationOAuthRoutesConfig,
  IntegrationProductRoutesConfig,
  IntegrationProviderExecutionRoutesConfig,
  IntegrationRouteHandler,
  OAuthRouteConnectorActions,
} from "./routes";
